spring:
  application:
    name: observ_ex

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: "true"

server:
  port: 8080
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}