name: CI pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  run-shared-ci:
    uses: MrKravz/shared-ci-workflows/.github/workflows/ci.yaml@main
    with:
      build-tool: 'maven'
      working-directory: 'observ_ex'
      sonar-args: >
        -Dsonar.projectKey=MrKravz_observe_ex
        -Dsonar.organization=mrkravz
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        -Dsonar.coverage.exclusions=**/config/**,**/dto/**,**/model/**,**/exception/**,**/repository/**,**/mapper/**,**/*Application.java,**/util/**,**/client/**
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}